# If you added a file to your project add it to the build section in the Makefile
# Always start the line with a tab in Makefile, it is its syntax

build:
	git submodule update --init --recursive
	cmake -S . -B build
	cmake --build build -j 12
	g++ ./src/main.cpp -o ./bin/main

clean:
	rm -f ./bin/*

all: clean build

run:
	build
	./bin/main
	test

test:
	build
	ctest -C Debug --test-dir build --output-on-failure -j12