# If you added a file to your project add it to the build section in the Makefile
# Always start the line with a tab in Makefile, it is its syntax

build:
	gcc ./src/main.cpp -o ./bin/main.out

clean:
	rm -f ./bin/*.out

all: clean build

run:
	build
	./bin/main.out
	test

test:
	build
	ctest -C Debug --test-dir build --output-on-failure -j12