.DEFAULT_GOAL := Packet.cpp

all: clean test

Packet.cpp:
	clean
	git submodule update --init --recursive
	cmake -S . -B build
	cmake --build build -j 12
	$(CC) $(SOURCES) -o $(TARGET)

clean:
	rm -rf ./bin/*

run: Packet.cpp
	./bin/main

test: Packet.cpp
	ctest -C Debug --test-dir build --output-on-failure -j12